[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.27.16"

# Description
title = "Isaac Lab framework for Robot Learning"
description="Extension providing main framework interfaces and abstractions for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/isaac-sim/IsaacLab"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai"]

[dependencies]
"omni.isaac.core" = {}
"omni.replicator.core" = {}

[python.pipapi]
requirements = [
    "numpy",
    "prettytable==3.3.0",
    "tensordict",
    "toml",
    "hidapi",
    "gymnasium==0.29.0",
    "trimesh",
    "paho-mqtt",
    "paramiko"
]

modules = [
    "numpy",
    "prettytable",
    "tensordict",
    "toml",
    "hid",
    "gymnasium",
    "trimesh",
    "paho-mqtt",
    "paramiko"
]

use_online_index=true

[[python.module]]
name = "omni.isaac.lab"
